# Let prefix of method name set_ and get_
AccessorMethodName:
  Enabled: false

# Change limitation of method length
MethodLength:
  CountComments: true  # count full line comments?
  Max: 20

# Change limitation of the number of params
ParameterLists:
  Max: 7
  CountKeywordArgs: true

# Change limitation of AbcSize
AbcSize:
  Max: 21

# Change limitation of the number of '/' within %r
RegexpLiteral:
  MaxSlashes: 0

# # 数値の区切りをなくす
# NumericLiterals:
#   MinDigits: 20
