# Let prefix of method name set_ and get_
AccessorMethodName:
  Enabled: false

# Change limitation of method length
MethodLength:
  CountComments: true  # count full line comments?
  Max: 20

# Change limitation of module length
ModuleLength:
  Max: 300

# Change limitation of the number of params
ParameterLists:
  Max: 8
  CountKeywordArgs: false

# Change limitation of AbcSize
AbcSize:
  Max: 21

# Change numeric literals
NumericLiterals:
  MinDigits: 20
